# Generated by Django 5.0.4 on 2024-05-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_billingaddress_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
